
export const commodityText = `SOYABEAN EXTRACTING YELLOW 46% GAURANTEE BASIS. PROTEIN MIN. 46%, MOISTURE MAX. 12%, FIBRE MAX. 6%, SAND / SILICA MAX. 2%, (FREE FROM ANY ADULTRATION, OVERTOASTING, CASTOR TRACE, HUSK, LUMPS & FUNGUS) UPTO 45% PROTEIN SINGLE REBATE, BELOW 45% PROTEIN CUTTING ON PRO RATA). `;

export const placeOfDeliveryText = `AT PLLACHI`;

export const periodOfDeliveryText = `DELIVERY OF GOODS UPTO 07/05/2024.`;

export const paymentText = `PAYMENT WITHIN ONE WEEK.`;

export const termsConditionText = `PACKAGIN IN PP BAGS DELIVERED WEIGHT & QUALITY FINAL.`;

export const brokerageLiabilityText = `WE ARE SOLELY ACTING AS A BROKER ON BEHALF OF BOTH THE PARTIES AND HENCEFORTH WILL NOT BE HELD RESPONSIBLE FOR ANY ACT OF SELLER AND BUYER WHETHER IT MAY PERTAINING TO FINANCIAL, CIVIL OR CRIMINAL NATURE. NONE OF THE PARTY IS ENTITLED TO TAKE ANY LEGAL OR OTHER ACTION  AGAINST US; IF ANY PARTY DOES SO THEN SUCH ACTION WILL BE CONSIDERED AS \'NULLIFIED\' BY VIRTUAL OF THIS CLAUSE. HOWEVER, WE SHALL ALWAYS REMAIN AVAILABLE AS A WITNESS FOR THIS  CONTRACT. "SUBJECT TO MUMBAI JURIDICTION" ONLY.`

export const brokerageText = `AS USUAL.`;


